version: '3.8'

services:
  transmitter:
    container_name: websocket-transmitter
    build:
      context: ./transmitter
    environment:
      - PORT=${TRANSMITTER_PORT}
    ports:
      - "${TRANSMITTER_PORT}:${TRANSMITTER_PORT}"
    restart: unless-stopped

  receiver:
    container_name: websocket-receiver
    build:
      context: ./receiver
    environment:
      - PORT=${RECEIVER_PORT}
      - TRANSMITTER_URL=ws://transmitter:${TRANSMITTER_PORT}/stream
    ports:
      - "${RECEIVER_PORT}:${RECEIVER_PORT}"
    depends_on:
      - transmitter
    restart: unless-stopped

volumes:
  received-images: 