version: '3.8'

services:
  transmitter:
    container_name: websocket-transmitter
    build:
      context: ./transmitter
      dockerfile: Dockerfile
    env_file:
      - ./transmitter/.env
    ports:
      - "${TRANSMITTER_PORT}:8081"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8081/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  receiver:
    container_name: websocket-receiver
    build:
      context: ./receiver
      dockerfile: Dockerfile
    env_file:
      - ./receiver/.env
    ports:
      - "${RECEIVER_PORT}:8080"
    volumes:
      - received-images:/usr/src/app/received
    depends_on:
      transmitter:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  received-images: 